version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: feature_flag_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: feature_flag_api
    command: >
      sh -c "poetry run alembic upgrade head &&
             poetry run uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
    ports:
      - "8000:8000"
    environment:
      - DEPENDENCY_APP_POSTGRES_DSN=postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local