"""Create initial tables for feature flags and audit logs

Revision ID: 4d562540f475
Revises:
Create Date: 2025-07-21 21:04:32.450421

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d562540f475"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("CREATE", "UPDATE", "DELETE", name="auditaction"),
            nullable=False,
        ),
        sa.Column("actor", sa.String(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("target_entity", sa.String(), nullable=False),
        sa.Column("target_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_target_entity"),
        "audit_logs",
        ["target_entity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_target_id"), "audit_logs", ["target_id"], unique=False
    )
    op.create_table(
        "feature_flags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feature_flags_id"), "feature_flags", ["id"], unique=False)
    op.create_index(
        op.f("ix_feature_flags_name"), "feature_flags", ["name"], unique=True
    )
    op.create_table(
        "feature_dependency_association",
        sa.Column("dependent_feature_id", sa.Integer(), nullable=False),
        sa.Column("parent_feature_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dependent_feature_id"],
            ["feature_flags.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_feature_id"],
            ["feature_flags.id"],
        ),
        sa.PrimaryKeyConstraint("dependent_feature_id", "parent_feature_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feature_dependency_association")
    op.drop_index(op.f("ix_feature_flags_name"), table_name="feature_flags")
    op.drop_index(op.f("ix_feature_flags_id"), table_name="feature_flags")
    op.drop_table("feature_flags")
    op.drop_index(op.f("ix_audit_logs_target_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_target_entity"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
