"""drop the enum for audit log action

Revision ID: 6fa1c750a6bb
Revises: 4d562540f475
Create Date: 2025-07-22 01:21:07.111771

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6fa1c750a6bb"
down_revision: Union[str, Sequence[str], None] = "4d562540f475"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audit_logs",
        "action",
        existing_type=postgresql.ENUM("CREATE", "UPDATE", "DELETE", name="auditaction"),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audit_logs",
        "action",
        existing_type=sa.String(),
        type_=postgresql.ENUM("CREATE", "UPDATE", "DELETE", name="auditaction"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
